--------------------------------------------
-- Authorization Statements on Tables/Views 
--------------------------------------------

-- Note: Running this scripts requires administrator authority.

GRANT SELECT ON TABLE "CONFMGR"."CONFIGURATION" TO USER PWMUSER ;

GRANT SELECT ON TABLE "CONFMGR"."PROPERTY" TO USER PWMUSER ;

GRANT SELECT ON TABLE "CONFMGR"."NODECONFIGURATION" TO USER PWMUSER ;

GRANT SELECT ON TABLE "CONFMGR"."NODECONFIGURATION_CONFIGURATION" TO USER PWMUSER ;

GRANT SELECT ON TABLE "CONFMGR"."AUTHORIZATION" TO USER PWMUSER ;

GRANT SELECT ON TABLE "CONFMGR"."AGENT_HIERARCHY" TO USER PWMUSER ;


GRANT INSERT ON TABLE "CONFMGR"."CONFIGURATION" TO USER PWMUSER ;

GRANT INSERT ON TABLE "CONFMGR"."PROPERTY" TO USER PWMUSER ;

GRANT INSERT ON TABLE "CONFMGR"."NODECONFIGURATION" TO USER PWMUSER ;

GRANT INSERT ON TABLE "CONFMGR"."NODECONFIGURATION_CONFIGURATION" TO USER PWMUSER ;

GRANT INSERT ON TABLE "CONFMGR"."AUTHORIZATION" TO USER PWMUSER ;


GRANT UPDATE ON TABLE "CONFMGR"."CONFIGURATION" TO USER PWMUSER ;

GRANT UPDATE ON TABLE "CONFMGR"."PROPERTY" TO USER PWMUSER ;

GRANT UPDATE ON TABLE "CONFMGR"."NODECONFIGURATION" TO USER PWMUSER ;

GRANT UPDATE ON TABLE "CONFMGR"."NODECONFIGURATION_CONFIGURATION" TO USER PWMUSER ;

GRANT UPDATE ON TABLE "CONFMGR"."AUTHORIZATION" TO USER PWMUSER ;


GRANT DELETE ON TABLE "CONFMGR"."CONFIGURATION" TO USER PWMUSER ;

GRANT DELETE ON TABLE "CONFMGR"."PROPERTY" TO USER PWMUSER ;

GRANT DELETE ON TABLE "CONFMGR"."NODECONFIGURATION" TO USER PWMUSER ;

GRANT DELETE ON TABLE "CONFMGR"."NODECONFIGURATION_CONFIGURATION" TO USER PWMUSER ;

GRANT DELETE ON TABLE "CONFMGR"."AUTHORIZATION" TO USER PWMUSER ;

