--<ScriptOptions statementTerminator=";"/>

ALTER TABLE CONFMGR.AUTHORIZATION DROP CONSTRAINT AUTHORIZATION_NODECONFIGURATION_FK;

ALTER TABLE CONFMGR.CONFIGURATION DROP CONSTRAINT SQL120313151721510;

ALTER TABLE CONFMGR.NODECONFIGURATION_CONFIGURATION DROP CONSTRAINT SQL120313151721570;

ALTER TABLE CONFMGR.NODECONFIGURATION_CONFIGURATION DROP CONSTRAINT SQL120313151721590;

ALTER TABLE CONFMGR.PROPERTY DROP CONSTRAINT SQL120313151721600;

ALTER TABLE CONFMGR.AUTHORIZATION DROP CONSTRAINT AUTHORIZATION_PK;

ALTER TABLE CONFMGR.CONFIGURATION DROP CONSTRAINT SQL120321111709690;

ALTER TABLE CONFMGR.NODECONFIGURATION DROP CONSTRAINT SQL120321111710950;

ALTER TABLE CONFMGR.PROPERTY DROP CONSTRAINT SQL120321111711890;

DROP VIEW CONFMGR.AGENT_HIERARCHY;

DROP TABLE CONFMGR.AUTHORIZATION;

DROP TABLE CONFMGR.CONFIGURATION;

DROP TABLE CONFMGR.NODECONFIGURATION;

DROP TABLE CONFMGR.NODECONFIGURATION_CONFIGURATION;

DROP TABLE CONFMGR.PROPERTY;

DROP SCHEMA CONFMGR RESTRICT;

CREATE SCHEMA CONFMGR;

CREATE TABLE CONFMGR.AUTHORIZATION (
		USERID VARCHAR(254) NOT NULL,
		NODEID VARCHAR(254) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE CONFMGR.CONFIGURATION (
		CLUSTER_ID VARCHAR(254) NOT NULL,
		CONFIG_ID VARCHAR(254) NOT NULL,
		PID VARCHAR(254),
		TEMPLATE SMALLINT,
		TYPE SMALLINT,
		PARENT_CLUSTER_ID VARCHAR(254),
		PARENT_CONFIG_ID VARCHAR(254)
	)
	DATA CAPTURE NONE;

CREATE TABLE CONFMGR.NODECONFIGURATION (
		NODEID VARCHAR(254) NOT NULL,
		DESCRIPTION VARCHAR(254),
		NAME VARCHAR(254),
		UPDATED SMALLINT
	)
	DATA CAPTURE NONE;

CREATE TABLE CONFMGR.NODECONFIGURATION_CONFIGURATION (
		NODECONFIGURATION_NODEID VARCHAR(254),
		CONFIGURATIONLIST_CLUSTER_ID VARCHAR(254),
		CONFIGURATIONLIST_CONFIG_ID VARCHAR(254)
	)
	DATA CAPTURE NONE;

CREATE TABLE CONFMGR.PROPERTY (
		CLUSTER_ID VARCHAR(254) NOT NULL,
		CONFIG_ID VARCHAR(254) NOT NULL,
		NAME VARCHAR(254) NOT NULL,
		VALUE VARCHAR(3072),
		TYPE SMALLINT NOT NULL
	)
	DATA CAPTURE NONE;

ALTER TABLE CONFMGR.AUTHORIZATION ADD CONSTRAINT AUTHORIZATION_PK PRIMARY KEY
	(USERID,
	 NODEID);

ALTER TABLE CONFMGR.CONFIGURATION ADD CONSTRAINT SQL120321111709690 PRIMARY KEY
	(CLUSTER_ID,
	 CONFIG_ID);

ALTER TABLE CONFMGR.NODECONFIGURATION ADD CONSTRAINT SQL120321111710950 PRIMARY KEY
	(NODEID);

ALTER TABLE CONFMGR.PROPERTY ADD CONSTRAINT SQL120321111711890 PRIMARY KEY
	(CLUSTER_ID,
	 CONFIG_ID,
	 NAME);

ALTER TABLE CONFMGR.AUTHORIZATION ADD CONSTRAINT AUTHORIZATION_NODECONFIGURATION_FK FOREIGN KEY
	(NODEID)
	REFERENCES CONFMGR.NODECONFIGURATION
	(NODEID);

ALTER TABLE CONFMGR.CONFIGURATION ADD CONSTRAINT SQL120313151721510 FOREIGN KEY
	(PARENT_CLUSTER_ID,
	 PARENT_CONFIG_ID)
	REFERENCES CONFMGR.CONFIGURATION
	(CLUSTER_ID,
	 CONFIG_ID);

ALTER TABLE CONFMGR.NODECONFIGURATION_CONFIGURATION ADD CONSTRAINT SQL120313151721570 FOREIGN KEY
	(NODECONFIGURATION_NODEID)
	REFERENCES CONFMGR.NODECONFIGURATION
	(NODEID);

ALTER TABLE CONFMGR.NODECONFIGURATION_CONFIGURATION ADD CONSTRAINT SQL120313151721590 FOREIGN KEY
	(CONFIGURATIONLIST_CLUSTER_ID,
	 CONFIGURATIONLIST_CONFIG_ID)
	REFERENCES CONFMGR.CONFIGURATION
	(CLUSTER_ID,
	 CONFIG_ID);

ALTER TABLE CONFMGR.PROPERTY ADD CONSTRAINT SQL120313151721600 FOREIGN KEY
	(CLUSTER_ID,
	 CONFIG_ID)
	REFERENCES CONFMGR.CONFIGURATION
	(CLUSTER_ID,
	 CONFIG_ID);

CREATE VIEW CONFMGR.AGENT_HIERARCHY (CLUSTER_ID, CONFIG_ID, AGENT_ID, AGENT_PARENT) AS
SELECT AGENTS.CLUSTER_ID, AGENTS.CONFIG_ID,AGENTS.VALUE AS AGENT_ID, (CASE WHEN PROP2.VALUE = '' THEN NULL ELSE PROP2.VALUE END) AS AGENT_PARENT FROM
(SELECT PROP.CLUSTER_ID, PROP.CONFIG_ID, PROP.NAME, PROP.VALUE FROM CONFMGR.PROPERTY PROP 
INNER JOIN CONFMGR.CONFIGURATION CONF ON CONF.CLUSTER_ID = PROP.CLUSTER_ID AND CONF.CONFIG_ID = PROP.CONFIG_ID
WHERE CONF.template = '0' AND (PROP.NAME = 'id')) AS AGENTS
INNER JOIN CONFMGR."PROPERTY" PROP2 ON AGENTS.CLUSTER_ID = PROP2.CLUSTER_ID AND AGENTS.CONFIG_ID = PROP2.CONFIG_ID AND PROP2.NAME = 'matcher.id';
